# Generated by Django 3.2.18 on 2023-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0005_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='./perfil/plantita.png', null=True, upload_to='perfil'),
        ),
    ]
