# Generated by Django 3.2.18 on 2023-06-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0006_alter_perfil_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publica.producto')),
                ('ambiente', models.CharField(choices=[('Sol', 'Sol'), ('Sombra', 'Sombra'), ('Interior', 'Interior'), ('Exterior', 'Exterior')], default='Interior', max_length=10)),
            ],
            bases=('publica.producto',),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
