# Generated by Django 3.2.18 on 2023-06-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0008_factura_productofactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.CharField(max_length=164)),
                ('grupos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publica.grupoplanta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publica.planta')),
            ],
        ),
        migrations.AddField(
            model_name='grupoplanta',
            name='members',
            field=models.ManyToManyField(through='publica.TipoPlanta', to='publica.Planta'),
        ),
    ]
