# Generated by Django 3.2.18 on 2023-06-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publica', '0009_auto_20230622_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupoplanta',
            old_name='name',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='grupoplanta',
            old_name='members',
            new_name='descripcion',
        ),
    ]
